package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Allergies generated by hbm2java
 */
public class Allergies  implements java.io.Serializable {


     private Integer allergyid;
     private String type;
     private String name;
     private String possibleRxns;
     private String suggestedTreatment;

    public Allergies() {
    }

    public Allergies(String type, String name, String possibleRxns, String suggestedTreatment) {
       this.type = type;
       this.name = name;
       this.possibleRxns = possibleRxns;
       this.suggestedTreatment = suggestedTreatment;
    }
   
    public Integer getAllergyid() {
        return this.allergyid;
    }
    
    public void setAllergyid(Integer allergyid) {
        this.allergyid = allergyid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPossibleRxns() {
        return this.possibleRxns;
    }
    
    public void setPossibleRxns(String possibleRxns) {
        this.possibleRxns = possibleRxns;
    }
    public String getSuggestedTreatment() {
        return this.suggestedTreatment;
    }
    
    public void setSuggestedTreatment(String suggestedTreatment) {
        this.suggestedTreatment = suggestedTreatment;
    }




}


