package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AppointmentType generated by hbm2java
 */
public class AppointmentType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String staffId;
     private Date dateAdded;

    public AppointmentType() {
    }

    public AppointmentType(String name, String description, String staffId, Date dateAdded) {
       this.name = name;
       this.description = description;
       this.staffId = staffId;
       this.dateAdded = dateAdded;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


