package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * ArchivedRefRangeUni generated by hbm2java
 */
public class ArchivedRefRangeUni  implements java.io.Serializable {


     private Integer id;
     private int detailedinvRefrangeTypeId;
     private int selected;
     private String lowerRefRange;
     private String upperRefRange;
     private String paragraphic;
     private String orderid;
     private int patienttreatmentid;

    public ArchivedRefRangeUni() {
    }

	
    public ArchivedRefRangeUni(int detailedinvRefrangeTypeId, int selected, String orderid, int patienttreatmentid) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
        this.selected = selected;
        this.orderid = orderid;
        this.patienttreatmentid = patienttreatmentid;
    }
    public ArchivedRefRangeUni(int detailedinvRefrangeTypeId, int selected, String lowerRefRange, String upperRefRange, String paragraphic, String orderid, int patienttreatmentid) {
       this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
       this.selected = selected;
       this.lowerRefRange = lowerRefRange;
       this.upperRefRange = upperRefRange;
       this.paragraphic = paragraphic;
       this.orderid = orderid;
       this.patienttreatmentid = patienttreatmentid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDetailedinvRefrangeTypeId() {
        return this.detailedinvRefrangeTypeId;
    }
    
    public void setDetailedinvRefrangeTypeId(int detailedinvRefrangeTypeId) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
    }
    public int getSelected() {
        return this.selected;
    }
    
    public void setSelected(int selected) {
        this.selected = selected;
    }
    public String getLowerRefRange() {
        return this.lowerRefRange;
    }
    
    public void setLowerRefRange(String lowerRefRange) {
        this.lowerRefRange = lowerRefRange;
    }
    public String getUpperRefRange() {
        return this.upperRefRange;
    }
    
    public void setUpperRefRange(String upperRefRange) {
        this.upperRefRange = upperRefRange;
    }
    public String getParagraphic() {
        return this.paragraphic;
    }
    
    public void setParagraphic(String paragraphic) {
        this.paragraphic = paragraphic;
    }
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    public int getPatienttreatmentid() {
        return this.patienttreatmentid;
    }
    
    public void setPatienttreatmentid(int patienttreatmentid) {
        this.patienttreatmentid = patienttreatmentid;
    }




}


