package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * ArchivedRefRangeDet generated by hbm2java
 */
public class ArchivedRefRangeDet  implements java.io.Serializable {


     private int id;
     private int detailedinvRefrangeTypeId;
     private String detFrom;
     private String detTo;
     private String MLower;
     private String MUpper;
     private String FLower;
     private String FUpper;
     private String oerderid;
     private int patienttreatmentid;

    public ArchivedRefRangeDet() {
    }

    public ArchivedRefRangeDet(int id, int detailedinvRefrangeTypeId, String detFrom, String detTo, String MLower, String MUpper, String FLower, String FUpper, String oerderid, int patienttreatmentid) {
       this.id = id;
       this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
       this.detFrom = detFrom;
       this.detTo = detTo;
       this.MLower = MLower;
       this.MUpper = MUpper;
       this.FLower = FLower;
       this.FUpper = FUpper;
       this.oerderid = oerderid;
       this.patienttreatmentid = patienttreatmentid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDetailedinvRefrangeTypeId() {
        return this.detailedinvRefrangeTypeId;
    }
    
    public void setDetailedinvRefrangeTypeId(int detailedinvRefrangeTypeId) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
    }
    public String getDetFrom() {
        return this.detFrom;
    }
    
    public void setDetFrom(String detFrom) {
        this.detFrom = detFrom;
    }
    public String getDetTo() {
        return this.detTo;
    }
    
    public void setDetTo(String detTo) {
        this.detTo = detTo;
    }
    public String getMLower() {
        return this.MLower;
    }
    
    public void setMLower(String MLower) {
        this.MLower = MLower;
    }
    public String getMUpper() {
        return this.MUpper;
    }
    
    public void setMUpper(String MUpper) {
        this.MUpper = MUpper;
    }
    public String getFLower() {
        return this.FLower;
    }
    
    public void setFLower(String FLower) {
        this.FLower = FLower;
    }
    public String getFUpper() {
        return this.FUpper;
    }
    
    public void setFUpper(String FUpper) {
        this.FUpper = FUpper;
    }
    public String getOerderid() {
        return this.oerderid;
    }
    
    public void setOerderid(String oerderid) {
        this.oerderid = oerderid;
    }
    public int getPatienttreatmentid() {
        return this.patienttreatmentid;
    }
    
    public void setPatienttreatmentid(int patienttreatmentid) {
        this.patienttreatmentid = patienttreatmentid;
    }




}


