package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Bed generated by hbm2java
 */
public class Bed  implements java.io.Serializable {


     private Integer bedid;
     private String description;
     private boolean occuppied;
     private String wardOrRoom;

    public Bed() {
    }

    public Bed(String description, boolean occuppied, String wardOrRoom) {
       this.description = description;
       this.occuppied = occuppied;
       this.wardOrRoom = wardOrRoom;
    }
   
    public Integer getBedid() {
        return this.bedid;
    }
    
    public void setBedid(Integer bedid) {
        this.bedid = bedid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isOccuppied() {
        return this.occuppied;
    }
    
    public void setOccuppied(boolean occuppied) {
        this.occuppied = occuppied;
    }
    public String getWardOrRoom() {
        return this.wardOrRoom;
    }
    
    public void setWardOrRoom(String wardOrRoom) {
        this.wardOrRoom = wardOrRoom;
    }




}


