package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * CompanyProfile generated by hbm2java
 */
public class CompanyProfile  implements java.io.Serializable {


     private String companyid;
     private String comapnyname;
     private String servicenumber;
     private String telephone;
     private String address;
     private String eclaimnumber;
     private String clinicFolderCode;
     private String diagnosticsFolderCode;
     private int clinicFolderStartNumber;
     private int diagnosticFolderStartNumber;
     private int clinicFolderStartActive;
     private int labFolderStartActive;
     private boolean labReportHeaderActive;
     private boolean labReportFooterActive;

    public CompanyProfile() {
    }

    public CompanyProfile(String companyid, String comapnyname, String servicenumber, String telephone, String address, String eclaimnumber, String clinicFolderCode, String diagnosticsFolderCode, int clinicFolderStartNumber, int diagnosticFolderStartNumber, int clinicFolderStartActive, int labFolderStartActive, boolean labReportHeaderActive, boolean labReportFooterActive) {
       this.companyid = companyid;
       this.comapnyname = comapnyname;
       this.servicenumber = servicenumber;
       this.telephone = telephone;
       this.address = address;
       this.eclaimnumber = eclaimnumber;
       this.clinicFolderCode = clinicFolderCode;
       this.diagnosticsFolderCode = diagnosticsFolderCode;
       this.clinicFolderStartNumber = clinicFolderStartNumber;
       this.diagnosticFolderStartNumber = diagnosticFolderStartNumber;
       this.clinicFolderStartActive = clinicFolderStartActive;
       this.labFolderStartActive = labFolderStartActive;
       this.labReportHeaderActive = labReportHeaderActive;
       this.labReportFooterActive = labReportFooterActive;
    }
   
    public String getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    public String getComapnyname() {
        return this.comapnyname;
    }
    
    public void setComapnyname(String comapnyname) {
        this.comapnyname = comapnyname;
    }
    public String getServicenumber() {
        return this.servicenumber;
    }
    
    public void setServicenumber(String servicenumber) {
        this.servicenumber = servicenumber;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEclaimnumber() {
        return this.eclaimnumber;
    }
    
    public void setEclaimnumber(String eclaimnumber) {
        this.eclaimnumber = eclaimnumber;
    }
    public String getClinicFolderCode() {
        return this.clinicFolderCode;
    }
    
    public void setClinicFolderCode(String clinicFolderCode) {
        this.clinicFolderCode = clinicFolderCode;
    }
    public String getDiagnosticsFolderCode() {
        return this.diagnosticsFolderCode;
    }
    
    public void setDiagnosticsFolderCode(String diagnosticsFolderCode) {
        this.diagnosticsFolderCode = diagnosticsFolderCode;
    }
    public int getClinicFolderStartNumber() {
        return this.clinicFolderStartNumber;
    }
    
    public void setClinicFolderStartNumber(int clinicFolderStartNumber) {
        this.clinicFolderStartNumber = clinicFolderStartNumber;
    }
    public int getDiagnosticFolderStartNumber() {
        return this.diagnosticFolderStartNumber;
    }
    
    public void setDiagnosticFolderStartNumber(int diagnosticFolderStartNumber) {
        this.diagnosticFolderStartNumber = diagnosticFolderStartNumber;
    }
    public int getClinicFolderStartActive() {
        return this.clinicFolderStartActive;
    }
    
    public void setClinicFolderStartActive(int clinicFolderStartActive) {
        this.clinicFolderStartActive = clinicFolderStartActive;
    }
    public int getLabFolderStartActive() {
        return this.labFolderStartActive;
    }
    
    public void setLabFolderStartActive(int labFolderStartActive) {
        this.labFolderStartActive = labFolderStartActive;
    }
    public boolean isLabReportHeaderActive() {
        return this.labReportHeaderActive;
    }
    
    public void setLabReportHeaderActive(boolean labReportHeaderActive) {
        this.labReportHeaderActive = labReportHeaderActive;
    }
    public boolean isLabReportFooterActive() {
        return this.labReportFooterActive;
    }
    
    public void setLabReportFooterActive(boolean labReportFooterActive) {
        this.labReportFooterActive = labReportFooterActive;
    }




}


