package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * CoreGhanaGroupings generated by hbm2java
 */
public class CoreGhanaGroupings  implements java.io.Serializable {


     private Integer groupingid;
     private String coreGdrg;
     private String diagnosticGroup;
     private String description;

    public CoreGhanaGroupings() {
    }

    public CoreGhanaGroupings(String coreGdrg, String diagnosticGroup, String description) {
       this.coreGdrg = coreGdrg;
       this.diagnosticGroup = diagnosticGroup;
       this.description = description;
    }
   
    public Integer getGroupingid() {
        return this.groupingid;
    }
    
    public void setGroupingid(Integer groupingid) {
        this.groupingid = groupingid;
    }
    public String getCoreGdrg() {
        return this.coreGdrg;
    }
    
    public void setCoreGdrg(String coreGdrg) {
        this.coreGdrg = coreGdrg;
    }
    public String getDiagnosticGroup() {
        return this.diagnosticGroup;
    }
    
    public void setDiagnosticGroup(String diagnosticGroup) {
        this.diagnosticGroup = diagnosticGroup;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


