package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * DiagnosisSymptoms generated by hbm2java
 */
public class DiagnosisSymptoms  implements java.io.Serializable {


     private Integer id;
     private int diagnosisId;
     private int symptomsId;

    public DiagnosisSymptoms() {
    }

    public DiagnosisSymptoms(int diagnosisId, int symptomsId) {
       this.diagnosisId = diagnosisId;
       this.symptomsId = symptomsId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDiagnosisId() {
        return this.diagnosisId;
    }
    
    public void setDiagnosisId(int diagnosisId) {
        this.diagnosisId = diagnosisId;
    }
    public int getSymptomsId() {
        return this.symptomsId;
    }
    
    public void setSymptomsId(int symptomsId) {
        this.symptomsId = symptomsId;
    }




}


