package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * DiagnosticGroupings generated by hbm2java
 */
public class DiagnosticGroupings  implements java.io.Serializable {


     private String code;
     private String descriptio;

    public DiagnosticGroupings() {
    }

    public DiagnosticGroupings(String code, String descriptio) {
       this.code = code;
       this.descriptio = descriptio;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescriptio() {
        return this.descriptio;
    }
    
    public void setDescriptio(String descriptio) {
        this.descriptio = descriptio;
    }




}


