package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Dosagemonitor generated by hbm2java
 */
public class Dosagemonitor  implements java.io.Serializable {


     private Integer id;
     private String treatmentId;
     private int visitid;
     private int quantity;
     private String nurse;
     private Date date;
     private String time;

    public Dosagemonitor() {
    }

    public Dosagemonitor(String treatmentId, int visitid, int quantity, String nurse, Date date, String time) {
       this.treatmentId = treatmentId;
       this.visitid = visitid;
       this.quantity = quantity;
       this.nurse = nurse;
       this.date = date;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTreatmentId() {
        return this.treatmentId;
    }
    
    public void setTreatmentId(String treatmentId) {
        this.treatmentId = treatmentId;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getNurse() {
        return this.nurse;
    }
    
    public void setNurse(String nurse) {
        this.nurse = nurse;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


