package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Drugtype generated by hbm2java
 */
public class Drugtype  implements java.io.Serializable {


     private Integer id;
     private String drugType;

    public Drugtype() {
    }

    public Drugtype(String drugType) {
       this.drugType = drugType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDrugType() {
        return this.drugType;
    }
    
    public void setDrugType(String drugType) {
        this.drugType = drugType;
    }




}


