package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Facility generated by hbm2java
 */
public class Facility  implements java.io.Serializable {


     private Integer id;
     private String doctorIncharge;
     private String facilityName;

    public Facility() {
    }

    public Facility(String doctorIncharge, String facilityName) {
       this.doctorIncharge = doctorIncharge;
       this.facilityName = facilityName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDoctorIncharge() {
        return this.doctorIncharge;
    }
    
    public void setDoctorIncharge(String doctorIncharge) {
        this.doctorIncharge = doctorIncharge;
    }
    public String getFacilityName() {
        return this.facilityName;
    }
    
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }




}


