package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * GeneralSettings generated by hbm2java
 */
public class GeneralSettings  implements java.io.Serializable {


     private Integer id;
     private String name;
     private boolean value;
     private Date dateAdded;
     private String staffId;

    public GeneralSettings() {
    }

    public GeneralSettings(String name, boolean value, Date dateAdded, String staffId) {
       this.name = name;
       this.value = value;
       this.dateAdded = dateAdded;
       this.staffId = staffId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isValue() {
        return this.value;
    }
    
    public void setValue(boolean value) {
        this.value = value;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }




}


