package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * InPatientBills generated by hbm2java
 */
public class InPatientBills  implements java.io.Serializable {


     private int visitid;
     private String patientid;
     private double totalBill;
     private double amountPaid;
     private String status;

    public InPatientBills() {
    }

    public InPatientBills(int visitid, String patientid, double totalBill, double amountPaid, String status) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.totalBill = totalBill;
       this.amountPaid = amountPaid;
       this.status = status;
    }
   
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public double getTotalBill() {
        return this.totalBill;
    }
    
    public void setTotalBill(double totalBill) {
        this.totalBill = totalBill;
    }
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


