package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * InvestigationResistantSusc generated by hbm2java
 */
public class InvestigationResistantSusc  implements java.io.Serializable {


     private Integer id;
     private int ptreatmentId;
     private int susceptibleTo;
     private int resistantTo;

    public InvestigationResistantSusc() {
    }

    public InvestigationResistantSusc(int ptreatmentId, int susceptibleTo, int resistantTo) {
       this.ptreatmentId = ptreatmentId;
       this.susceptibleTo = susceptibleTo;
       this.resistantTo = resistantTo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPtreatmentId() {
        return this.ptreatmentId;
    }
    
    public void setPtreatmentId(int ptreatmentId) {
        this.ptreatmentId = ptreatmentId;
    }
    public int getSusceptibleTo() {
        return this.susceptibleTo;
    }
    
    public void setSusceptibleTo(int susceptibleTo) {
        this.susceptibleTo = susceptibleTo;
    }
    public int getResistantTo() {
        return this.resistantTo;
    }
    
    public void setResistantTo(int resistantTo) {
        this.resistantTo = resistantTo;
    }




}


