package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * InvestigationAntibiotic generated by hbm2java
 */
public class InvestigationAntibiotic  implements java.io.Serializable {


     private Integer id;
     private int invId;
     private int antibioticId;
     private String status;

    public InvestigationAntibiotic() {
    }

    public InvestigationAntibiotic(int invId, int antibioticId, String status) {
       this.invId = invId;
       this.antibioticId = antibioticId;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getInvId() {
        return this.invId;
    }
    
    public void setInvId(int invId) {
        this.invId = invId;
    }
    public int getAntibioticId() {
        return this.antibioticId;
    }
    
    public void setAntibioticId(int antibioticId) {
        this.antibioticId = antibioticId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


