package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ItemsTable generated by hbm2java
 */
public class ItemsTable  implements java.io.Serializable {


     private String batchNumber;
     private String code;
     private int quantity;
     private int manufacturer;
     private double purchasingprice;
     private int supplier;
     private double dispensaryprice;
     private Date expiryDate;
     private double nhisprice;
     private double pharmacyprice;
     private int reorderLevel;
     private int emergencyLevel;
     private String locationId;
     private double laboratoryprice;

    public ItemsTable() {
    }

    public ItemsTable(String batchNumber, String code, int quantity, int manufacturer, double purchasingprice, int supplier, double dispensaryprice, Date expiryDate, double nhisprice, double pharmacyprice, int reorderLevel, int emergencyLevel, String locationId, double laboratoryprice) {
       this.batchNumber = batchNumber;
       this.code = code;
       this.quantity = quantity;
       this.manufacturer = manufacturer;
       this.purchasingprice = purchasingprice;
       this.supplier = supplier;
       this.dispensaryprice = dispensaryprice;
       this.expiryDate = expiryDate;
       this.nhisprice = nhisprice;
       this.pharmacyprice = pharmacyprice;
       this.reorderLevel = reorderLevel;
       this.emergencyLevel = emergencyLevel;
       this.locationId = locationId;
       this.laboratoryprice = laboratoryprice;
    }
   
    public String getBatchNumber() {
        return this.batchNumber;
    }
    
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(int manufacturer) {
        this.manufacturer = manufacturer;
    }
    public double getPurchasingprice() {
        return this.purchasingprice;
    }
    
    public void setPurchasingprice(double purchasingprice) {
        this.purchasingprice = purchasingprice;
    }
    public int getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(int supplier) {
        this.supplier = supplier;
    }
    public double getDispensaryprice() {
        return this.dispensaryprice;
    }
    
    public void setDispensaryprice(double dispensaryprice) {
        this.dispensaryprice = dispensaryprice;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public double getNhisprice() {
        return this.nhisprice;
    }
    
    public void setNhisprice(double nhisprice) {
        this.nhisprice = nhisprice;
    }
    public double getPharmacyprice() {
        return this.pharmacyprice;
    }
    
    public void setPharmacyprice(double pharmacyprice) {
        this.pharmacyprice = pharmacyprice;
    }
    public int getReorderLevel() {
        return this.reorderLevel;
    }
    
    public void setReorderLevel(int reorderLevel) {
        this.reorderLevel = reorderLevel;
    }
    public int getEmergencyLevel() {
        return this.emergencyLevel;
    }
    
    public void setEmergencyLevel(int emergencyLevel) {
        this.emergencyLevel = emergencyLevel;
    }
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
    public double getLaboratoryprice() {
        return this.laboratoryprice;
    }
    
    public void setLaboratoryprice(double laboratoryprice) {
        this.laboratoryprice = laboratoryprice;
    }




}


