package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * LabAntibiotic generated by hbm2java
 */
public class LabAntibiotic  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer orderNum;

    public LabAntibiotic() {
    }

	
    public LabAntibiotic(String name) {
        this.name = name;
    }
    public LabAntibiotic(String name, Integer orderNum) {
       this.name = name;
       this.orderNum = orderNum;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }




}


