package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Laborders generated by hbm2java
 */
public class Laborders  implements java.io.Serializable {


     private String orderid;
     private String patientid;
     private String facility;
     private String fromdoc;
     private String todoc;
     private String physician;
     private double totalAmount;
     private Date orderdate;
     private Date donedate;
     private Boolean viewed;
     private int visitid;
     private String done;
     private Double amountpaid;
     private Double outstanding;
     private String scrutinized;
     private Date date;
     private String receivedBy;

    public Laborders() {
    }

	
    public Laborders(String orderid, String patientid, String facility, String fromdoc, String physician, double totalAmount, Date orderdate, int visitid, String done, String scrutinized, Date date, String receivedBy) {
        this.orderid = orderid;
        this.patientid = patientid;
        this.facility = facility;
        this.fromdoc = fromdoc;
        this.physician = physician;
        this.totalAmount = totalAmount;
        this.orderdate = orderdate;
        this.visitid = visitid;
        this.done = done;
        this.scrutinized = scrutinized;
        this.date = date;
        this.receivedBy = receivedBy;
    }
    public Laborders(String orderid, String patientid, String facility, String fromdoc, String todoc, String physician, double totalAmount, Date orderdate, Date donedate, Boolean viewed, int visitid, String done, Double amountpaid, Double outstanding, String scrutinized, Date date, String receivedBy) {
       this.orderid = orderid;
       this.patientid = patientid;
       this.facility = facility;
       this.fromdoc = fromdoc;
       this.todoc = todoc;
       this.physician = physician;
       this.totalAmount = totalAmount;
       this.orderdate = orderdate;
       this.donedate = donedate;
       this.viewed = viewed;
       this.visitid = visitid;
       this.done = done;
       this.amountpaid = amountpaid;
       this.outstanding = outstanding;
       this.scrutinized = scrutinized;
       this.date = date;
       this.receivedBy = receivedBy;
    }
   
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    public String getTodoc() {
        return this.todoc;
    }
    
    public void setTodoc(String todoc) {
        this.todoc = todoc;
    }
    public String getPhysician() {
        return this.physician;
    }
    
    public void setPhysician(String physician) {
        this.physician = physician;
    }
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public Date getDonedate() {
        return this.donedate;
    }
    
    public void setDonedate(Date donedate) {
        this.donedate = donedate;
    }
    public Boolean getViewed() {
        return this.viewed;
    }
    
    public void setViewed(Boolean viewed) {
        this.viewed = viewed;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getDone() {
        return this.done;
    }
    
    public void setDone(String done) {
        this.done = done;
    }
    public Double getAmountpaid() {
        return this.amountpaid;
    }
    
    public void setAmountpaid(Double amountpaid) {
        this.amountpaid = amountpaid;
    }
    public Double getOutstanding() {
        return this.outstanding;
    }
    
    public void setOutstanding(Double outstanding) {
        this.outstanding = outstanding;
    }
    public String getScrutinized() {
        return this.scrutinized;
    }
    
    public void setScrutinized(String scrutinized) {
        this.scrutinized = scrutinized;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getReceivedBy() {
        return this.receivedBy;
    }
    
    public void setReceivedBy(String receivedBy) {
        this.receivedBy = receivedBy;
    }




}


