package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Labtypes generated by hbm2java
 */
public class Labtypes  implements java.io.Serializable {


     private Integer labTypeId;
     private String labCode;
     private String labType;
     private Integer orderNum;
     private int active;

    public Labtypes() {
    }

	
    public Labtypes(String labCode, String labType, int active) {
        this.labCode = labCode;
        this.labType = labType;
        this.active = active;
    }
    public Labtypes(String labCode, String labType, Integer orderNum, int active) {
       this.labCode = labCode;
       this.labType = labType;
       this.orderNum = orderNum;
       this.active = active;
    }
   
    public Integer getLabTypeId() {
        return this.labTypeId;
    }
    
    public void setLabTypeId(Integer labTypeId) {
        this.labTypeId = labTypeId;
    }
    public String getLabCode() {
        return this.labCode;
    }
    
    public void setLabCode(String labCode) {
        this.labCode = labCode;
    }
    public String getLabType() {
        return this.labType;
    }
    
    public void setLabType(String labType) {
        this.labType = labType;
    }
    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


