package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Manufacturer generated by hbm2java
 */
public class Manufacturer  implements java.io.Serializable {


     private Integer manufacturerid;
     private String manufaturer;
     private String telephone;
     private String address;
     private String email;

    public Manufacturer() {
    }

	
    public Manufacturer(String manufaturer) {
        this.manufaturer = manufaturer;
    }
    public Manufacturer(String manufaturer, String telephone, String address, String email) {
       this.manufaturer = manufaturer;
       this.telephone = telephone;
       this.address = address;
       this.email = email;
    }
   
    public Integer getManufacturerid() {
        return this.manufacturerid;
    }
    
    public void setManufacturerid(Integer manufacturerid) {
        this.manufacturerid = manufacturerid;
    }
    public String getManufaturer() {
        return this.manufaturer;
    }
    
    public void setManufaturer(String manufaturer) {
        this.manufaturer = manufaturer;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


