package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Nhistreatment generated by hbm2java
 */
public class Nhistreatment  implements java.io.Serializable {


     private Integer treatmentid;
     private String medicine;
     private String unitPrice;
     private double price;
     private String gdrg;
     private int therapeuticGroup;
     private String diagnosticgroup;

    public Nhistreatment() {
    }

    public Nhistreatment(String medicine, String unitPrice, double price, String gdrg, int therapeuticGroup, String diagnosticgroup) {
       this.medicine = medicine;
       this.unitPrice = unitPrice;
       this.price = price;
       this.gdrg = gdrg;
       this.therapeuticGroup = therapeuticGroup;
       this.diagnosticgroup = diagnosticgroup;
    }
   
    public Integer getTreatmentid() {
        return this.treatmentid;
    }
    
    public void setTreatmentid(Integer treatmentid) {
        this.treatmentid = treatmentid;
    }
    public String getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }
    public String getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getGdrg() {
        return this.gdrg;
    }
    
    public void setGdrg(String gdrg) {
        this.gdrg = gdrg;
    }
    public int getTherapeuticGroup() {
        return this.therapeuticGroup;
    }
    
    public void setTherapeuticGroup(int therapeuticGroup) {
        this.therapeuticGroup = therapeuticGroup;
    }
    public String getDiagnosticgroup() {
        return this.diagnosticgroup;
    }
    
    public void setDiagnosticgroup(String diagnosticgroup) {
        this.diagnosticgroup = diagnosticgroup;
    }




}


