package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patienttreatment generated by hbm2java
 */
public class Patienttreatment  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private String code;
     private String treatmentid;
     private String dosage;
     private int visitationid;
     private Date date;
     private double price;
     private Integer quantity;
     private String type;
     private String note;
     private String dispensed;
     private double amounpaid;
     private String orderid;
     private boolean copaid;
     private boolean isPrivate;
     private double secondaryAmount;
     private double privateAmount;

    public Patienttreatment() {
    }

	
    public Patienttreatment(String patientid, String code, String treatmentid, String dosage, int visitationid, Date date, double price, String dispensed, double amounpaid, String orderid, boolean copaid, boolean isPrivate, double secondaryAmount, double privateAmount) {
        this.patientid = patientid;
        this.code = code;
        this.treatmentid = treatmentid;
        this.dosage = dosage;
        this.visitationid = visitationid;
        this.date = date;
        this.price = price;
        this.dispensed = dispensed;
        this.amounpaid = amounpaid;
        this.orderid = orderid;
        this.copaid = copaid;
        this.isPrivate = isPrivate;
        this.secondaryAmount = secondaryAmount;
        this.privateAmount = privateAmount;
    }
    public Patienttreatment(String patientid, String code, String treatmentid, String dosage, int visitationid, Date date, double price, Integer quantity, String type, String note, String dispensed, double amounpaid, String orderid, boolean copaid, boolean isPrivate, double secondaryAmount, double privateAmount) {
       this.patientid = patientid;
       this.code = code;
       this.treatmentid = treatmentid;
       this.dosage = dosage;
       this.visitationid = visitationid;
       this.date = date;
       this.price = price;
       this.quantity = quantity;
       this.type = type;
       this.note = note;
       this.dispensed = dispensed;
       this.amounpaid = amounpaid;
       this.orderid = orderid;
       this.copaid = copaid;
       this.isPrivate = isPrivate;
       this.secondaryAmount = secondaryAmount;
       this.privateAmount = privateAmount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getTreatmentid() {
        return this.treatmentid;
    }
    
    public void setTreatmentid(String treatmentid) {
        this.treatmentid = treatmentid;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public int getVisitationid() {
        return this.visitationid;
    }
    
    public void setVisitationid(int visitationid) {
        this.visitationid = visitationid;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getDispensed() {
        return this.dispensed;
    }
    
    public void setDispensed(String dispensed) {
        this.dispensed = dispensed;
    }
    public double getAmounpaid() {
        return this.amounpaid;
    }
    
    public void setAmounpaid(double amounpaid) {
        this.amounpaid = amounpaid;
    }
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    public boolean isIsPrivate() {
        return this.isPrivate;
    }
    
    public void setIsPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }
    public double getSecondaryAmount() {
        return this.secondaryAmount;
    }
    
    public void setSecondaryAmount(double secondaryAmount) {
        this.secondaryAmount = secondaryAmount;
    }
    public double getPrivateAmount() {
        return this.privateAmount;
    }
    
    public void setPrivateAmount(double privateAmount) {
        this.privateAmount = privateAmount;
    }




}


