package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * PatientBed generated by hbm2java
 */
public class PatientBed  implements java.io.Serializable {


     private int visitid;
     private String patientid;
     private int bedid;

    public PatientBed() {
    }

    public PatientBed(int visitid, String patientid, int bedid) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.bedid = bedid;
    }
   
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public int getBedid() {
        return this.bedid;
    }
    
    public void setBedid(int bedid) {
        this.bedid = bedid;
    }




}


