package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * PatientAllergies generated by hbm2java
 */
public class PatientAllergies  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private int allergyid;

    public PatientAllergies() {
    }

    public PatientAllergies(String patientid, int allergyid) {
       this.patientid = patientid;
       this.allergyid = allergyid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public int getAllergyid() {
        return this.allergyid;
    }
    
    public void setAllergyid(int allergyid) {
        this.allergyid = allergyid;
    }




}


