package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PatientRegistration generated by hbm2java
 */
public class PatientRegistration  implements java.io.Serializable {


     private Integer regId;
     private String patientId;
     private boolean paymentStatus;
     private double amountPaid;
     private Date datePaid;
     private int regFeeId;
     private boolean copaid;
     private double secondaryPayment;
     private boolean personallySupported;
     private double personalSupportAmount;

    public PatientRegistration() {
    }

	
    public PatientRegistration(String patientId, boolean paymentStatus, double amountPaid, int regFeeId, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
        this.patientId = patientId;
        this.paymentStatus = paymentStatus;
        this.amountPaid = amountPaid;
        this.regFeeId = regFeeId;
        this.copaid = copaid;
        this.secondaryPayment = secondaryPayment;
        this.personallySupported = personallySupported;
        this.personalSupportAmount = personalSupportAmount;
    }
    public PatientRegistration(String patientId, boolean paymentStatus, double amountPaid, Date datePaid, int regFeeId, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
       this.patientId = patientId;
       this.paymentStatus = paymentStatus;
       this.amountPaid = amountPaid;
       this.datePaid = datePaid;
       this.regFeeId = regFeeId;
       this.copaid = copaid;
       this.secondaryPayment = secondaryPayment;
       this.personallySupported = personallySupported;
       this.personalSupportAmount = personalSupportAmount;
    }
   
    public Integer getRegId() {
        return this.regId;
    }
    
    public void setRegId(Integer regId) {
        this.regId = regId;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public boolean isPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(boolean paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    public int getRegFeeId() {
        return this.regFeeId;
    }
    
    public void setRegFeeId(int regFeeId) {
        this.regFeeId = regFeeId;
    }
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    public double getSecondaryPayment() {
        return this.secondaryPayment;
    }
    
    public void setSecondaryPayment(double secondaryPayment) {
        this.secondaryPayment = secondaryPayment;
    }
    public boolean isPersonallySupported() {
        return this.personallySupported;
    }
    
    public void setPersonallySupported(boolean personallySupported) {
        this.personallySupported = personallySupported;
    }
    public double getPersonalSupportAmount() {
        return this.personalSupportAmount;
    }
    
    public void setPersonalSupportAmount(double personalSupportAmount) {
        this.personalSupportAmount = personalSupportAmount;
    }




}


