package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Patientconsultation generated by hbm2java
 */
public class Patientconsultation  implements java.io.Serializable {


     private Integer id;
     private int visitid;
     private int typeid;
     private Double amountpaid;
     private String status;
     private boolean copaid;
     private double secondaryPayment;
     private boolean personallySupported;
     private double personalSupportAmount;

    public Patientconsultation() {
    }

	
    public Patientconsultation(int visitid, int typeid, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
        this.visitid = visitid;
        this.typeid = typeid;
        this.copaid = copaid;
        this.secondaryPayment = secondaryPayment;
        this.personallySupported = personallySupported;
        this.personalSupportAmount = personalSupportAmount;
    }
    public Patientconsultation(int visitid, int typeid, Double amountpaid, String status, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
       this.visitid = visitid;
       this.typeid = typeid;
       this.amountpaid = amountpaid;
       this.status = status;
       this.copaid = copaid;
       this.secondaryPayment = secondaryPayment;
       this.personallySupported = personallySupported;
       this.personalSupportAmount = personalSupportAmount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public int getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(int typeid) {
        this.typeid = typeid;
    }
    public Double getAmountpaid() {
        return this.amountpaid;
    }
    
    public void setAmountpaid(Double amountpaid) {
        this.amountpaid = amountpaid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    public double getSecondaryPayment() {
        return this.secondaryPayment;
    }
    
    public void setSecondaryPayment(double secondaryPayment) {
        this.secondaryPayment = secondaryPayment;
    }
    public boolean isPersonallySupported() {
        return this.personallySupported;
    }
    
    public void setPersonallySupported(boolean personallySupported) {
        this.personallySupported = personallySupported;
    }
    public double getPersonalSupportAmount() {
        return this.personalSupportAmount;
    }
    
    public void setPersonalSupportAmount(double personalSupportAmount) {
        this.personalSupportAmount = personalSupportAmount;
    }




}


