package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * PatientBills generated by hbm2java
 */
public class PatientBills  implements java.io.Serializable {


     private int visitid;
     private String patientid;
     private double totalBill;
     private double amountPaid;
     private String status;
     private int laborderDiscount;
     private int pharmorderDiscount;
     private int medicalDiscount;
     private int procedureDiscount;

    public PatientBills() {
    }

    public PatientBills(int visitid, String patientid, double totalBill, double amountPaid, String status, int laborderDiscount, int pharmorderDiscount, int medicalDiscount, int procedureDiscount) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.totalBill = totalBill;
       this.amountPaid = amountPaid;
       this.status = status;
       this.laborderDiscount = laborderDiscount;
       this.pharmorderDiscount = pharmorderDiscount;
       this.medicalDiscount = medicalDiscount;
       this.procedureDiscount = procedureDiscount;
    }
   
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public double getTotalBill() {
        return this.totalBill;
    }
    
    public void setTotalBill(double totalBill) {
        this.totalBill = totalBill;
    }
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getLaborderDiscount() {
        return this.laborderDiscount;
    }
    
    public void setLaborderDiscount(int laborderDiscount) {
        this.laborderDiscount = laborderDiscount;
    }
    public int getPharmorderDiscount() {
        return this.pharmorderDiscount;
    }
    
    public void setPharmorderDiscount(int pharmorderDiscount) {
        this.pharmorderDiscount = pharmorderDiscount;
    }
    public int getMedicalDiscount() {
        return this.medicalDiscount;
    }
    
    public void setMedicalDiscount(int medicalDiscount) {
        this.medicalDiscount = medicalDiscount;
    }
    public int getProcedureDiscount() {
        return this.procedureDiscount;
    }
    
    public void setProcedureDiscount(int procedureDiscount) {
        this.procedureDiscount = procedureDiscount;
    }




}


