package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PatientProcedure generated by hbm2java
 */
public class PatientProcedure  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private String procedureCode;
     private Date date;
     private int visitid;
     private double amountpaid;
     private boolean copaid;
     private boolean isPrivate;
     private double secondaryAmount;
     private double privateAmount;

    public PatientProcedure() {
    }

    public PatientProcedure(String patientid, String procedureCode, Date date, int visitid, double amountpaid, boolean copaid, boolean isPrivate, double secondaryAmount, double privateAmount) {
       this.patientid = patientid;
       this.procedureCode = procedureCode;
       this.date = date;
       this.visitid = visitid;
       this.amountpaid = amountpaid;
       this.copaid = copaid;
       this.isPrivate = isPrivate;
       this.secondaryAmount = secondaryAmount;
       this.privateAmount = privateAmount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getProcedureCode() {
        return this.procedureCode;
    }
    
    public void setProcedureCode(String procedureCode) {
        this.procedureCode = procedureCode;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public double getAmountpaid() {
        return this.amountpaid;
    }
    
    public void setAmountpaid(double amountpaid) {
        this.amountpaid = amountpaid;
    }
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    public boolean isIsPrivate() {
        return this.isPrivate;
    }
    
    public void setIsPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }
    public double getSecondaryAmount() {
        return this.secondaryAmount;
    }
    
    public void setSecondaryAmount(double secondaryAmount) {
        this.secondaryAmount = secondaryAmount;
    }
    public double getPrivateAmount() {
        return this.privateAmount;
    }
    
    public void setPrivateAmount(double privateAmount) {
        this.privateAmount = privateAmount;
    }




}


