package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PaymentObject generated by hbm2java
 */
public class PaymentObject  implements java.io.Serializable {


     private Integer id;
     private String transactionId;
     private String transactionType;
     private String itemId;
     private String primarySponsorId;
     private Double primarySponsorAmount;
     private String secSponsorId;
     private Double secSponsorAmount;
     private String outOfPocketId;
     private Double outOfPocketAmount;
     private Date datePaid;
     private Date timePaid;
     private String staffId;
     private String patientId;
     private String status;
     private double totalAmountPaid;
     private String unknownTwo;

    public PaymentObject() {
    }

	
    public PaymentObject(String transactionId, String transactionType, Date datePaid, Date timePaid, String staffId, String patientId, String status, double totalAmountPaid) {
        this.transactionId = transactionId;
        this.transactionType = transactionType;
        this.datePaid = datePaid;
        this.timePaid = timePaid;
        this.staffId = staffId;
        this.patientId = patientId;
        this.status = status;
        this.totalAmountPaid = totalAmountPaid;
    }
    public PaymentObject(String transactionId, String transactionType, String itemId, String primarySponsorId, Double primarySponsorAmount, String secSponsorId, Double secSponsorAmount, String outOfPocketId, Double outOfPocketAmount, Date datePaid, Date timePaid, String staffId, String patientId, String status, double totalAmountPaid, String unknownTwo) {
       this.transactionId = transactionId;
       this.transactionType = transactionType;
       this.itemId = itemId;
       this.primarySponsorId = primarySponsorId;
       this.primarySponsorAmount = primarySponsorAmount;
       this.secSponsorId = secSponsorId;
       this.secSponsorAmount = secSponsorAmount;
       this.outOfPocketId = outOfPocketId;
       this.outOfPocketAmount = outOfPocketAmount;
       this.datePaid = datePaid;
       this.timePaid = timePaid;
       this.staffId = staffId;
       this.patientId = patientId;
       this.status = status;
       this.totalAmountPaid = totalAmountPaid;
       this.unknownTwo = unknownTwo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }
    public String getPrimarySponsorId() {
        return this.primarySponsorId;
    }
    
    public void setPrimarySponsorId(String primarySponsorId) {
        this.primarySponsorId = primarySponsorId;
    }
    public Double getPrimarySponsorAmount() {
        return this.primarySponsorAmount;
    }
    
    public void setPrimarySponsorAmount(Double primarySponsorAmount) {
        this.primarySponsorAmount = primarySponsorAmount;
    }
    public String getSecSponsorId() {
        return this.secSponsorId;
    }
    
    public void setSecSponsorId(String secSponsorId) {
        this.secSponsorId = secSponsorId;
    }
    public Double getSecSponsorAmount() {
        return this.secSponsorAmount;
    }
    
    public void setSecSponsorAmount(Double secSponsorAmount) {
        this.secSponsorAmount = secSponsorAmount;
    }
    public String getOutOfPocketId() {
        return this.outOfPocketId;
    }
    
    public void setOutOfPocketId(String outOfPocketId) {
        this.outOfPocketId = outOfPocketId;
    }
    public Double getOutOfPocketAmount() {
        return this.outOfPocketAmount;
    }
    
    public void setOutOfPocketAmount(Double outOfPocketAmount) {
        this.outOfPocketAmount = outOfPocketAmount;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    public Date getTimePaid() {
        return this.timePaid;
    }
    
    public void setTimePaid(Date timePaid) {
        this.timePaid = timePaid;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public double getTotalAmountPaid() {
        return this.totalAmountPaid;
    }
    
    public void setTotalAmountPaid(double totalAmountPaid) {
        this.totalAmountPaid = totalAmountPaid;
    }
    public String getUnknownTwo() {
        return this.unknownTwo;
    }
    
    public void setUnknownTwo(String unknownTwo) {
        this.unknownTwo = unknownTwo;
    }




}


