package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private Integer permissionid;
     private String permission;
     private int departmentid;

    public Permission() {
    }

    public Permission(String permission, int departmentid) {
       this.permission = permission;
       this.departmentid = departmentid;
    }
   
    public Integer getPermissionid() {
        return this.permissionid;
    }
    
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    public int getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(int departmentid) {
        this.departmentid = departmentid;
    }




}


