package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pharmorder generated by hbm2java
 */
public class Pharmorder  implements java.io.Serializable {


     private String orderid;
     private String patientid;
     private String fromdoc;
     private Date orderdate;
     private Date dispenseddate;
     private Integer visitid;
     private String dispensed;
     private Double amoutpaid;
     private Double outstanding;

    public Pharmorder() {
    }

	
    public Pharmorder(String orderid, String patientid, Date orderdate) {
        this.orderid = orderid;
        this.patientid = patientid;
        this.orderdate = orderdate;
    }
    public Pharmorder(String orderid, String patientid, String fromdoc, Date orderdate, Date dispenseddate, Integer visitid, String dispensed, Double amoutpaid, Double outstanding) {
       this.orderid = orderid;
       this.patientid = patientid;
       this.fromdoc = fromdoc;
       this.orderdate = orderdate;
       this.dispenseddate = dispenseddate;
       this.visitid = visitid;
       this.dispensed = dispensed;
       this.amoutpaid = amoutpaid;
       this.outstanding = outstanding;
    }
   
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public Date getDispenseddate() {
        return this.dispenseddate;
    }
    
    public void setDispenseddate(Date dispenseddate) {
        this.dispenseddate = dispenseddate;
    }
    public Integer getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(Integer visitid) {
        this.visitid = visitid;
    }
    public String getDispensed() {
        return this.dispensed;
    }
    
    public void setDispensed(String dispensed) {
        this.dispensed = dispensed;
    }
    public Double getAmoutpaid() {
        return this.amoutpaid;
    }
    
    public void setAmoutpaid(Double amoutpaid) {
        this.amoutpaid = amoutpaid;
    }
    public Double getOutstanding() {
        return this.outstanding;
    }
    
    public void setOutstanding(Double outstanding) {
        this.outstanding = outstanding;
    }




}


