package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Procedureorders generated by hbm2java
 */
public class Procedureorders  implements java.io.Serializable {


     private Integer orderid;
     private int visitid;
     private String patientid;
     private double total;
     private double amoutpaid;
     private String status;

    public Procedureorders() {
    }

    public Procedureorders(int visitid, String patientid, double total, double amoutpaid, String status) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.total = total;
       this.amoutpaid = amoutpaid;
       this.status = status;
    }
   
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public double getAmoutpaid() {
        return this.amoutpaid;
    }
    
    public void setAmoutpaid(double amoutpaid) {
        this.amoutpaid = amoutpaid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


