package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * ProfileDetails generated by hbm2java
 */
public class ProfileDetails  implements java.io.Serializable {


     private Integer detailId;
     private int profileId;
     private int labId;

    public ProfileDetails() {
    }

    public ProfileDetails(int profileId, int labId) {
       this.profileId = profileId;
       this.labId = labId;
    }
   
    public Integer getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }
    public int getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }




}


