package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer profileId;
     private String profileDescription;
     private double profileAmount;

    public Profile() {
    }

    public Profile(String profileDescription, double profileAmount) {
       this.profileDescription = profileDescription;
       this.profileAmount = profileAmount;
    }
   
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public String getProfileDescription() {
        return this.profileDescription;
    }
    
    public void setProfileDescription(String profileDescription) {
        this.profileDescription = profileDescription;
    }
    public double getProfileAmount() {
        return this.profileAmount;
    }
    
    public void setProfileAmount(double profileAmount) {
        this.profileAmount = profileAmount;
    }




}


