package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * ReferringDoctors generated by hbm2java
 */
public class ReferringDoctors  implements java.io.Serializable {


     private Integer id;
     private String nameName;
     private String facility;

    public ReferringDoctors() {
    }

    public ReferringDoctors(String nameName, String facility) {
       this.nameName = nameName;
       this.facility = facility;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameName() {
        return this.nameName;
    }
    
    public void setNameName(String nameName) {
        this.nameName = nameName;
    }
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }




}


