package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * RefRangeUni generated by hbm2java
 */
public class RefRangeUni  implements java.io.Serializable {


     private Integer id;
     private int detailedinvRefrangeTypeId;
     private int selected;
     private String lowerRefRange;
     private String upperRefRange;
     private String paragraphic;

    public RefRangeUni() {
    }

	
    public RefRangeUni(int detailedinvRefrangeTypeId, int selected) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
        this.selected = selected;
    }
    public RefRangeUni(int detailedinvRefrangeTypeId, int selected, String lowerRefRange, String upperRefRange, String paragraphic) {
       this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
       this.selected = selected;
       this.lowerRefRange = lowerRefRange;
       this.upperRefRange = upperRefRange;
       this.paragraphic = paragraphic;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDetailedinvRefrangeTypeId() {
        return this.detailedinvRefrangeTypeId;
    }
    
    public void setDetailedinvRefrangeTypeId(int detailedinvRefrangeTypeId) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
    }
    public int getSelected() {
        return this.selected;
    }
    
    public void setSelected(int selected) {
        this.selected = selected;
    }
    public String getLowerRefRange() {
        return this.lowerRefRange;
    }
    
    public void setLowerRefRange(String lowerRefRange) {
        this.lowerRefRange = lowerRefRange;
    }
    public String getUpperRefRange() {
        return this.upperRefRange;
    }
    
    public void setUpperRefRange(String upperRefRange) {
        this.upperRefRange = upperRefRange;
    }
    public String getParagraphic() {
        return this.paragraphic;
    }
    
    public void setParagraphic(String paragraphic) {
        this.paragraphic = paragraphic;
    }




}


