package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RegFee generated by hbm2java
 */
public class RegFee  implements java.io.Serializable {


     private Integer id;
     private double regFee;
     private String userId;
     private Date dateAdded;
     private String status;

    public RegFee() {
    }

    public RegFee(double regFee, String userId, Date dateAdded, String status) {
       this.regFee = regFee;
       this.userId = userId;
       this.dateAdded = dateAdded;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getRegFee() {
        return this.regFee;
    }
    
    public void setRegFee(double regFee) {
        this.regFee = regFee;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


