package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Requisitions generated by hbm2java
 */
public class Requisitions  implements java.io.Serializable {


     private Integer requisitionid;
     private String itemcode;
     private String orderer;
     private Date orderdate;
     private Date deliverydate;
     private String deliverer;
     private Date deliverytime;
     private String status;
     private String unit;
     private int redquantity;
     private int deliveredquantity;

    public Requisitions() {
    }

	
    public Requisitions(String itemcode, String orderer, Date orderdate, String status, String unit, int redquantity, int deliveredquantity) {
        this.itemcode = itemcode;
        this.orderer = orderer;
        this.orderdate = orderdate;
        this.status = status;
        this.unit = unit;
        this.redquantity = redquantity;
        this.deliveredquantity = deliveredquantity;
    }
    public Requisitions(String itemcode, String orderer, Date orderdate, Date deliverydate, String deliverer, Date deliverytime, String status, String unit, int redquantity, int deliveredquantity) {
       this.itemcode = itemcode;
       this.orderer = orderer;
       this.orderdate = orderdate;
       this.deliverydate = deliverydate;
       this.deliverer = deliverer;
       this.deliverytime = deliverytime;
       this.status = status;
       this.unit = unit;
       this.redquantity = redquantity;
       this.deliveredquantity = deliveredquantity;
    }
   
    public Integer getRequisitionid() {
        return this.requisitionid;
    }
    
    public void setRequisitionid(Integer requisitionid) {
        this.requisitionid = requisitionid;
    }
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }
    public String getOrderer() {
        return this.orderer;
    }
    
    public void setOrderer(String orderer) {
        this.orderer = orderer;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    public String getDeliverer() {
        return this.deliverer;
    }
    
    public void setDeliverer(String deliverer) {
        this.deliverer = deliverer;
    }
    public Date getDeliverytime() {
        return this.deliverytime;
    }
    
    public void setDeliverytime(Date deliverytime) {
        this.deliverytime = deliverytime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public int getRedquantity() {
        return this.redquantity;
    }
    
    public void setRedquantity(int redquantity) {
        this.redquantity = redquantity;
    }
    public int getDeliveredquantity() {
        return this.deliveredquantity;
    }
    
    public void setDeliveredquantity(int deliveredquantity) {
        this.deliveredquantity = deliveredquantity;
    }




}


