package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Specimen generated by hbm2java
 */
public class Specimen  implements java.io.Serializable {


     private Integer specimenId;
     private String specimen;

    public Specimen() {
    }

    public Specimen(String specimen) {
       this.specimen = specimen;
    }
   
    public Integer getSpecimenId() {
        return this.specimenId;
    }
    
    public void setSpecimenId(Integer specimenId) {
        this.specimenId = specimenId;
    }
    public String getSpecimen() {
        return this.specimen;
    }
    
    public void setSpecimen(String specimen) {
        this.specimen = specimen;
    }




}


