package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Sponsorhipdetails generated by hbm2java
 */
public class Sponsorhipdetails  implements java.io.Serializable {


     private String patientid;
     private String membershipid;
     private String type;
     private String benefitplan;
     private String sponsorid;
     private String dependentnumber;
     private String secondarySponsor;
     private String secondaryType;
     private String secondaryBenefitplan;
     private String secondaryMembership;

    public Sponsorhipdetails() {
    }

	
    public Sponsorhipdetails(String patientid) {
        this.patientid = patientid;
    }
    public Sponsorhipdetails(String patientid, String membershipid, String type, String benefitplan, String sponsorid, String dependentnumber, String secondarySponsor, String secondaryType, String secondaryBenefitplan, String secondaryMembership) {
       this.patientid = patientid;
       this.membershipid = membershipid;
       this.type = type;
       this.benefitplan = benefitplan;
       this.sponsorid = sponsorid;
       this.dependentnumber = dependentnumber;
       this.secondarySponsor = secondarySponsor;
       this.secondaryType = secondaryType;
       this.secondaryBenefitplan = secondaryBenefitplan;
       this.secondaryMembership = secondaryMembership;
    }
   
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getMembershipid() {
        return this.membershipid;
    }
    
    public void setMembershipid(String membershipid) {
        this.membershipid = membershipid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getBenefitplan() {
        return this.benefitplan;
    }
    
    public void setBenefitplan(String benefitplan) {
        this.benefitplan = benefitplan;
    }
    public String getSponsorid() {
        return this.sponsorid;
    }
    
    public void setSponsorid(String sponsorid) {
        this.sponsorid = sponsorid;
    }
    public String getDependentnumber() {
        return this.dependentnumber;
    }
    
    public void setDependentnumber(String dependentnumber) {
        this.dependentnumber = dependentnumber;
    }
    public String getSecondarySponsor() {
        return this.secondarySponsor;
    }
    
    public void setSecondarySponsor(String secondarySponsor) {
        this.secondarySponsor = secondarySponsor;
    }
    public String getSecondaryType() {
        return this.secondaryType;
    }
    
    public void setSecondaryType(String secondaryType) {
        this.secondaryType = secondaryType;
    }
    public String getSecondaryBenefitplan() {
        return this.secondaryBenefitplan;
    }
    
    public void setSecondaryBenefitplan(String secondaryBenefitplan) {
        this.secondaryBenefitplan = secondaryBenefitplan;
    }
    public String getSecondaryMembership() {
        return this.secondaryMembership;
    }
    
    public void setSecondaryMembership(String secondaryMembership) {
        this.secondaryMembership = secondaryMembership;
    }




}


