package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Sponsorship generated by hbm2java
 */
public class Sponsorship  implements java.io.Serializable {


     private String sponshorshipid;
     private String sponsorname;
     private String type;
     private String address;
     private String contact;
     private String email;
     private Double labmarkup;
     private Double treatmentMarkup;
     private double markupTreatPercentage;
     private double markupLabPercentage;

    public Sponsorship() {
    }

	
    public Sponsorship(String sponshorshipid, double markupTreatPercentage, double markupLabPercentage) {
        this.sponshorshipid = sponshorshipid;
        this.markupTreatPercentage = markupTreatPercentage;
        this.markupLabPercentage = markupLabPercentage;
    }
    public Sponsorship(String sponshorshipid, String sponsorname, String type, String address, String contact, String email, Double labmarkup, Double treatmentMarkup, double markupTreatPercentage, double markupLabPercentage) {
       this.sponshorshipid = sponshorshipid;
       this.sponsorname = sponsorname;
       this.type = type;
       this.address = address;
       this.contact = contact;
       this.email = email;
       this.labmarkup = labmarkup;
       this.treatmentMarkup = treatmentMarkup;
       this.markupTreatPercentage = markupTreatPercentage;
       this.markupLabPercentage = markupLabPercentage;
    }
   
    public String getSponshorshipid() {
        return this.sponshorshipid;
    }
    
    public void setSponshorshipid(String sponshorshipid) {
        this.sponshorshipid = sponshorshipid;
    }
    public String getSponsorname() {
        return this.sponsorname;
    }
    
    public void setSponsorname(String sponsorname) {
        this.sponsorname = sponsorname;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Double getLabmarkup() {
        return this.labmarkup;
    }
    
    public void setLabmarkup(Double labmarkup) {
        this.labmarkup = labmarkup;
    }
    public Double getTreatmentMarkup() {
        return this.treatmentMarkup;
    }
    
    public void setTreatmentMarkup(Double treatmentMarkup) {
        this.treatmentMarkup = treatmentMarkup;
    }
    public double getMarkupTreatPercentage() {
        return this.markupTreatPercentage;
    }
    
    public void setMarkupTreatPercentage(double markupTreatPercentage) {
        this.markupTreatPercentage = markupTreatPercentage;
    }
    public double getMarkupLabPercentage() {
        return this.markupLabPercentage;
    }
    
    public void setMarkupLabPercentage(double markupLabPercentage) {
        this.markupLabPercentage = markupLabPercentage;
    }




}


