package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer supplierid;
     private String name;
     private String address;
     private String telephone;
     private String email;

    public Supplier() {
    }

	
    public Supplier(String name, String address) {
        this.name = name;
        this.address = address;
    }
    public Supplier(String name, String address, String telephone, String email) {
       this.name = name;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
    }
   
    public Integer getSupplierid() {
        return this.supplierid;
    }
    
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


