package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * TherapeuticGroup generated by hbm2java
 */
public class TherapeuticGroup  implements java.io.Serializable {


     private Integer theraid;
     private String description;

    public TherapeuticGroup() {
    }

    public TherapeuticGroup(String description) {
       this.description = description;
    }
   
    public Integer getTheraid() {
        return this.theraid;
    }
    
    public void setTheraid(Integer theraid) {
        this.theraid = theraid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


