package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TransitClinicLabs generated by hbm2java
 */
public class TransitClinicLabs  implements java.io.Serializable {


     private String orderid;
     private String patientid;
     private String fromdoc;
     private Date orderdate;
     private int visitid;
     private String done;

    public TransitClinicLabs() {
    }

    public TransitClinicLabs(String orderid, String patientid, String fromdoc, Date orderdate, int visitid, String done) {
       this.orderid = orderid;
       this.patientid = patientid;
       this.fromdoc = fromdoc;
       this.orderdate = orderdate;
       this.visitid = visitid;
       this.done = done;
    }
   
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getDone() {
        return this.done;
    }
    
    public void setDone(String done) {
        this.done = done;
    }




}


