package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * VisitSymptoms generated by hbm2java
 */
public class VisitSymptoms  implements java.io.Serializable {


     private Integer id;
     private int visitid;
     private String patientid;
     private int symptomid;
     private String note;

    public VisitSymptoms() {
    }

    public VisitSymptoms(int visitid, String patientid, int symptomid, String note) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.symptomid = symptomid;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public int getSymptomid() {
        return this.symptomid;
    }
    
    public void setSymptomid(int symptomid) {
        this.symptomid = symptomid;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


