package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Vitalcheck generated by hbm2java
 */
public class Vitalcheck  implements java.io.Serializable {


     private Integer id;
     private int visitid;
     private double pressure;
     private double temperature;
     private double systolic;
     private double diatolic;
     private String time;

    public Vitalcheck() {
    }

    public Vitalcheck(int visitid, double pressure, double temperature, double systolic, double diatolic, String time) {
       this.visitid = visitid;
       this.pressure = pressure;
       this.temperature = temperature;
       this.systolic = systolic;
       this.diatolic = diatolic;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public double getPressure() {
        return this.pressure;
    }
    
    public void setPressure(double pressure) {
        this.pressure = pressure;
    }
    public double getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(double temperature) {
        this.temperature = temperature;
    }
    public double getSystolic() {
        return this.systolic;
    }
    
    public void setSystolic(double systolic) {
        this.systolic = systolic;
    }
    public double getDiatolic() {
        return this.diatolic;
    }
    
    public void setDiatolic(double diatolic) {
        this.diatolic = diatolic;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


