package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Vitaltable generated by hbm2java
 */
public class Vitaltable  implements java.io.Serializable {


     private int vitalid;
     private String patientid;
     private Double temperature;
     private Double height;
     private Double weight;
     private Double sistolic;
     private Double diatolic;
     private Double pulse;
     private String otherSymptons;
     private Date date;

    public Vitaltable() {
    }

	
    public Vitaltable(int vitalid, String patientid, Date date) {
        this.vitalid = vitalid;
        this.patientid = patientid;
        this.date = date;
    }
    public Vitaltable(int vitalid, String patientid, Double temperature, Double height, Double weight, Double sistolic, Double diatolic, Double pulse, String otherSymptons, Date date) {
       this.vitalid = vitalid;
       this.patientid = patientid;
       this.temperature = temperature;
       this.height = height;
       this.weight = weight;
       this.sistolic = sistolic;
       this.diatolic = diatolic;
       this.pulse = pulse;
       this.otherSymptons = otherSymptons;
       this.date = date;
    }
   
    public int getVitalid() {
        return this.vitalid;
    }
    
    public void setVitalid(int vitalid) {
        this.vitalid = vitalid;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public Double getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }
    public Double getHeight() {
        return this.height;
    }
    
    public void setHeight(Double height) {
        this.height = height;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public Double getSistolic() {
        return this.sistolic;
    }
    
    public void setSistolic(Double sistolic) {
        this.sistolic = sistolic;
    }
    public Double getDiatolic() {
        return this.diatolic;
    }
    
    public void setDiatolic(Double diatolic) {
        this.diatolic = diatolic;
    }
    public Double getPulse() {
        return this.pulse;
    }
    
    public void setPulse(Double pulse) {
        this.pulse = pulse;
    }
    public String getOtherSymptons() {
        return this.otherSymptons;
    }
    
    public void setOtherSymptons(String otherSymptons) {
        this.otherSymptons = otherSymptons;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


