package entities;
// Generated 13-Aug-2013 12:01:58 by Hibernate Tools 3.2.1.GA



/**
 * Ward generated by hbm2java
 */
public class Ward  implements java.io.Serializable {


     private Integer wardid;
     private String wardname;
     private int numberofbeds;
     private int occupied;
     private double cost;
     private String type;

    public Ward() {
    }

    public Ward(String wardname, int numberofbeds, int occupied, double cost, String type) {
       this.wardname = wardname;
       this.numberofbeds = numberofbeds;
       this.occupied = occupied;
       this.cost = cost;
       this.type = type;
    }
   
    public Integer getWardid() {
        return this.wardid;
    }
    
    public void setWardid(Integer wardid) {
        this.wardid = wardid;
    }
    public String getWardname() {
        return this.wardname;
    }
    
    public void setWardname(String wardname) {
        this.wardname = wardname;
    }
    public int getNumberofbeds() {
        return this.numberofbeds;
    }
    
    public void setNumberofbeds(int numberofbeds) {
        this.numberofbeds = numberofbeds;
    }
    public int getOccupied() {
        return this.occupied;
    }
    
    public void setOccupied(int occupied) {
        this.occupied = occupied;
    }
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


